version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 1
    volumes:
      - .:/app  # mount current dir into container
    command: flask run --host=0.0.0.0
