version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      FLASK_APP: lib/app.py
      FLASK_DEBUG: 1
      DATABASE_HOST: reservationapp-postgres-1
      DATABASE_USER: barbro
      DATABASE_PASSWORD: blackmoor
      DATABASE_NAME: reservation_system
    volumes:
      - .:/app  # mount current dir into container
    command: python3 lib/app.py
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: reservationapp-postgres-1
    environment:
      POSTGRES_DB: reservation_system
      POSTGRES_USER: barbro
      POSTGRES_PASSWORD: blackmoor
    ports:
      - "54320:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
